### ISSUE TITLE
Crear pedido ajax a api publica para escribir datos

### ISSUE THREAD

**Issue by classkun** [Joc8k/EJERCICIOS-CON-APIS-PUBLICAS-#1]
- [ ] Conseguir una api publica que te permita escribir y leer en ella
- [ ] Crear un Crud en html que se vea competente
- [ ] Escribir en la api con AJAX
- [ ] Leer de la api con AJAX y mostrarlo en pantalla

**Comment by Joc8k** [comment]
TERMINADO !

**Comment by Joc8k** [comment]
TERMINADO !
